name: JobsPayHistory
main: payHistory.PayHistoryMain
version: 1.0
commands:
   ph:
       description: history command
       default: false
       usage: ph
   convert:
       description: Convert relics to 1.16 format
       default: false
       usage: convert